config/routes.rb
Speeedooo::Application.routes.draw do

  resources :users do
  		resources :tasks
  end

  root :to => "tasks#index"
  
  match "/auth/:provider/callback" => "sessions#callback" 
  match "/logout" => "sessions#destroy", :as => :logout

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
  attr_accessible :content, :limit, :title
  validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks
  attr_accessible :name, :provider, :uid
  
  def self.create_with_omniauth(auth)
  	create!do |user|
  		user.provider = auth["provider"]
  		user.uid = auth["uid"]
  		
  		if user.provider == "facebook"
  			user.name = auth["info"]["name"]
  		else
  			user.name = auth["info"]["nickname"]
  		end
  		
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/tasks_controller.rb
# coding: utf-8

class TasksController < ApplicationController
	
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'task updated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper  
  def bootstrap_flash
   flash_messages = []
   flash.each do |type, message|
     # Skip Devise :timeout flag
     next if type == :timeout
     type = :success if type == :notice
     type = :error   if type == :alert
     text = content_tag(:div, 
              content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
              message, :class => "alert fade in alert-#{type}")
     flash_messages << text if message
   end
   flash_messages.join("\n").html_safe
 end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Speeedooo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Speeedooo</a>
          <div class="container-fluid nav-collapse">
            <ul id="user_nav" class="nav">
              <li>
          			<% if current_user %>
          				<%= current_user.name %>さんでログイン中です。 <%= link_to 'ログアウト', logout_path %>
          			<% else %>
          				<%= link_to "TwitterでLogin", "/auth/twitter" %>
          			<% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
          </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
			<!--
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
      	<br>
        <p>&copy;copyright <%= link_to 'speeedooo', '/' %> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4><%= f.label 'タイトル' %></h4>
    <%= f.text_field :title, :placeholder => "タスクの名前を記入"%>
  </div>
  <div class="field">
    <h4><%= f.label '内容' %></h4>
    <%= f.text_area :content, :rows => 10, :placeholder => "タスクの内容を記入" %>
  </div>
  <div class="field">
    <h4><%= f.label '期限' %></h4>
    <%= f.date_select :limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h3>タスクの編集</h3>

<%= render 'form' %>

<%= link_to 'タスクにもどる', @task %> |
<%= link_to 'トップにもどる', '/' %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>

<table class="table table-hover table-bordered">
  <tr style="background-color: #DFF0D8">
    <th>タイトル</th>
    <th>期限</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.title, task %></td>
    <td><%= task.limit %></td>
    <td><%= link_to '編集', edit_task_path(task) %></td>
    <td><%= link_to '削除', task, method: :delete, data: { confirm: '削除しますか?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'タスクを追加', new_task_path %>

app/views/tasks/new.html.erb
<h3>新規タスク</h3>

<%= render 'form' %>

<%= link_to 'トップにもどる', '/' %>

app/views/tasks/show.html.erb
<p id="notice"></p>

<table class="table table-bordered">
<tr>
	<th style="background-color: #DFF0D8" width="15%">タイトル</th>
	<td><%= @task.title %></td>
</tr>
<tr>
	<th style="background-color: #DFF0D8">内容</th>
	<td><pre><%= @task.content %></pre></td>
</tr>
<tr>
	<th style="background-color: #DFF0D8">期限</th>
	<td><%= @task.limit %></td>
</tr>
</table>

<%= link_to 'タスクを編集', edit_task_path(@task) %> |
<%= link_to 'トップにもどる', '/' %>